name: sequana_rnaseq

channels:
- conda-forge
- bioconda
- defaults
- r

dependencies:
- cutadapt
- atropos
- bowtie
- samtools>1.7
- bamtools
- bedtools
- bowtie2>=2.3
- fastqc
- subread
- fastp
- deeptools
- salmon
- star
- picard>2.20
- gffread
